name: Meu Primeiro Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar workload Aspire
        run: dotnet workload install aspire

      - name: Exibir mensagem
        run: echo "Olá Github, GitHub Actions está funcionando!"

      - name: Restaurar dependências
        run: dotnet restore src/CodeCafe.sln

      - name: Restaurar workloads do .NET
        run: dotnet workload restore --project src/CodeCafe.sln

      - name: Compilar o projeto
        run: dotnet build src/CodeCafe.sln --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test src/CodeCafe.sln --no-build --configuration Release

      - name: Publicar artefatos
        run: dotnet publish src/CodeCafe.sln --no-build --configuration Release --output ./publicacao

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: build-dotnet
          path: ./publicacao

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}